### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by jinfagang** [youhosi/nodebb-theme-oxide#13]
What should I do interms of this error:

```
["Expression"] but instead got null {"stack":"TypeError: Property consequent of ConditionalExpression expected node to be of a type [\"Expression\"] but instead got null\n    at Object.validate (/root/nodebb/node_modules/babel-types/lib/definitions/index.js:109:13)\n    at validate (/root/nodebb/node_modules/babel-types/lib/index.js:505:9)\n    at Object.builder (/root/nodebb/node_modules/babel-types/lib/index.js:466:7)\n    at Object.OpenIf (/root/nodebb/node_modules/benchpressjs/build/lib/compiler/compiler.js:105:14)\n    at compile (/root/nodebb/node_modules/benchpressjs/build/lib/compiler/compiler.js:146:49)\n    at Object.OpenIter (/root/nodebb/node_modules/benchpressjs/build/lib/compiler/compiler.js:118:246)\n    at compile (/root/nodebb/node_modules/benchpressjs/build/lib/compiler/compiler.js:146:49)\n    at compiler (/root/nodebb/node_modules/benchpressjs/build/lib/compiler/compiler.js:160:20)\n    at compileFallback (/root/nodebb/node_modules/benchpressjs/build/lib/precompile.js:32:17)\n    at Promise.try (/root/nodebb/node_modules/benchpressjs/build/lib/precompile.js:93:88)"}
```

I only have on Oxide theme now, I am pretty new to frontend and nodejs, could any body help me?

**Comment by youhosi** [comment]
Try update NodeBB to latest version (branch master)

**Comment by jinfagang** [comment]
thank you so much!
